version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[",]//g' | sed 's/version://g' | tr -d '[[:space:]]')
      - echo $PACKAGE_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building compilation container for api...
      - chmod +x entrypoint.sh
      - docker build -t toh .
      - docker tag toh:latest $ECR_URL:$PACKAGE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_URL:$PACKAGE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"api","imageUri":"%s"}]' $ECR_URL:$PACKAGE_VERSION > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
